development:
  api_url: 'http://localhost:3000/offers.json'
  api_key: 'b07a12df7d52e6c118e5d47d3f9e60135b109a1f'

test:
  api_url: 'http://localhost:3000/offers.json'
  api_key: 'b07a12df7d52e6c118e5d47d3f9e60135b109a1f'

production:
  api_url: 'http://ancient-waters-6498.herokuapp.com/offers.json'
  api_key: 'b07a12df7d52e6c118e5d47d3f9e60135b109a1f'

